### ISSUE TITLE
Incompatible with Essentials and Factions?

### ISSUE THREAD

**Issue by BlackBeltPanda** [XHawk87/Coinage#1]
Coinage version: 0.2.3
Spigot version: fa7cbf9-00eba53
Vault version: 1.5.2-b33

I have Essentials configured to give players money when they first join. Their balance remains at 0, however.

Also, when depositing money into a factions bank, the factions bank remains at 0 but the money is withdrawn from the player.

An example of depositing money into the Splat faction's bank:
![](http://i.gyazo.com/5e275c34bbd63966727f5525b53d044a.png)

**Comment by XHawk87** [comment]
Sorry, Coinage doesn't have any virtual currency banking support. It is designed to be used as a physical currency, stored in chests or other containers, or using the (experimental) moneybags feature.
